### ISSUE TITLE
Last time entry in project

### ISSUE THREAD

**Issue by jvlobo** [kanet77/togglv8#10]
Hi there.

I'm trying to retrieve the latest time entry from a specific project.

The only way I think I could do it is with the User method **my_time_entries** but this method doesn't retrieve all User's time entries. Currently the method is retrieving my last 10 time entries, and none of them are from the project I want to use.

There is another method or another way to retrieve the last entry from a specific project??

I hope I've explained it well. Thanks :)

**Comment by jvlobo** [comment]
Hi @kanet77 do you think you could help me out with this??

Thanks :)

**Comment by kanet77** [comment]
Hi @jvlobo. Sorry I didn't get back to you sooner.

I don't see a single API call to get the latest time entry for a given project. The best option I see is to filter time entries by time interval (say, working backwards one week at a time) until you see the project of interest.

I think the right answer is probably to use the [Reports API](https://github.com/toggl/toggl_api_docs/blob/master/reports.md) which I haven't yet had the time to implement and test.

**Comment by kanet77** [comment]
If you still have a need for this, TogglV8 now supports the Reports API. You might be able to simply iterate backward 30 days at a time (or some other interval) till you find one or more time entries.

**Comment by kanet77** [comment]
Closing because this is more a limitation of Toggl.com than the togglv8 library.
