### ISSUE TITLE
Broken method get_time_entries({start_date: @now - 1, end_date: @now + 1})

### ISSUE THREAD

**Issue by garmoshka-mo** [kanet77/togglv8#11]
Methods, which described in specs seems to be broken (Outdated API calls?)

https://github.com/kanet77/togglv8/blob/master/spec/lib/togglv8/time_entries_spec.rb

````
require 'togglv8'
require 'json'

config = JSON.parse(File.read('config.json'))

toggl    = TogglV8::API.new(config['toggl_api_token'])

@now = DateTime.now
r = toggl.get_time_entries({start_date: @now - 1, end_date: @now + 1})
r.each do |e|
  p e
  p '------'
end
````

Gives 400 response from server:
````
/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/togglv8-1.0.2/lib/togglv8.rb:93:in `_call_api': HTTP Status: 400 (RuntimeError)
	from /Users/garmoshka-mo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/togglv8-1.0.2/lib/togglv8.rb:100:in `get'
	from /Users/garmoshka-mo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/togglv8-1.0.2/lib/togglv8/time_entries.rb:82:in `get_time_entries'
	from import.rb:12:in `<main>'
````

**Comment by garmoshka-mo** [comment]
To be exact - same code but only without `({start_date: @now - 10, end_date: @now})` - works as expected
(though not very usable because returns tons of records)

**Comment by kanet77** [comment]
Are you using the latest version ([v1.0.2](https://rubygems.org/gems/togglv8/versions/1.0.2))? I'm able to run your code exactly as it's written.

```
$ ruby garmoshka-mo.rb
{"id"=>321144098, "guid"=>"a8cb8f08-0508-4d4b-8e19-d2a21e2bb292", "wid"=>1062195, "billable"=>false, "start"=>"2016-01-14T05:39:34+00:00", "stop"=>"2016-01-14T05:39:38+00:00", "duration"=>3, "description"=>"issue #11", "duronly"=>false, "at"=>"2016-01-14T05:39:38+00:00", "uid"=>1820939}
"------"
```

However, it looks like Toggl may have made an API change. I re-ran my latest Travis CI build without making any code changes and it failed.

I see 400 response codes relating to Task API calls and other errors relating to Projects. I see the same errors running tests locally. I'll take a look.

**Comment by kanet77** [comment]
I'm wrong about the cause of my errors. My Toggl subscription ran out and I was testing Pro features without a Pro account. Everything looks good in [Travis CI](https://travis-ci.org/kanet77/togglv8/builds/96371750) now.

On closer inspection I see that you do have v1.0.2 of togglv8. No guess why you're getting a 400. I'll see if there's an easy way to add better end-user debugging to the gem.

**Comment by garmoshka-mo** [comment]
When i have:
````
r = toggl.get_time_entries({start_date: @now - 1, end_date: @now + 1})
````

Here is what `full_resp` have:
````
#<Faraday::Response:0x007fbc008df158 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="Invalid start date\n" @url=#<URI::HTTPS https://www.toggl.com/api/v8/time_entries?end_date=2016-01-19T18%3A32%3A37+02%3A00&start_date=2016-01-17T18%3A32%3A37+02%3A00> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Content-Type"=>"application/json", "Authorization"=>"Basic --<CUT>--", "User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007fbc008df158 ...> @response_headers={"server"=>"nginx", "date"=>"Mon, 18 Jan 2016 16:32:24 GMT", "content-type"=>"text/plain; charset=utf-8", "content-length"=>"19", "connection"=>"close", "cache-control"=>"no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0", "x-content-type-options"=>"nosniff", "x-toggl-request-id"=>"8a2c9b0f-bc27-4272-7ebc-eea04c098429"} @status=400>>
````

So it says "Invalid start date"

And this - works:

```
r = toggl.get_time_entries({start_date: '2016-01-17', end_date: '2016-01-19'})
```

So i'll use custom formatting for my task, though probably someone else may meet same isssue

**Comment by kanet77** [comment]
Thanks for the debug output. It helped me recognize the problem was the '+' in your ISO8601-formatted time.

    end_date=2016-01-19T18%3A32%3A37+02%3A00&start_date=2016-01-17T18%3A32%3A37+02%3A00
                                    ^                                          ^

I didn't see this problem because I have a negative UTC offset.

Use v1.0.4 for the fix.

Also, you can now print the Faraday debug output to STDOUT by calling `toggl.debug(true)` (or simply `toggl.debug`).

**Comment by garmoshka-mo** [comment]
Thanx! 
Yeah, that debug option would simplify understanding of issues a lot
