### ISSUE TITLE
`requireParams': params[start] is required, params[duration] is required (ArgumentError)

### ISSUE THREAD

**Issue by jvlobo** [kanet77/togglv8#9]
Hi there.

I'm trying to run the example that you provide but I'm getting this error:

<img width="1149" alt="captura de pantalla 2015-12-11 a las 18 51 01" src="https://cloud.githubusercontent.com/assets/5671420/11751173/260cdaba-a038-11e5-8d73-a2b5fc5aa6e4.png">

This is the code:

![captura de pantalla 2015-12-11 a las 18 51 18](https://cloud.githubusercontent.com/assets/5671420/11751189/49084f18-a038-11e5-8c00-7fcfe7803605.png)

I don't know if I'm doing something wrong, but the code seems like in your example.

Thanks.

**Comment by kanet77** [comment]
I'll take a look this weekend.

I'll take a guess to get you unblocked. I think I switched to using only string keys instead of symbols.

Perhaps try this:

```
toggl_api.create_time_entry({
  'description' => "Workspace time entry",
  'wid' => workspace_id,
  'duration' => 1200,
  'start' => "2015-08-18T01:13:40.000Z",
  'created_with' => "My awesome Ruby application"})
```

**Comment by jvlobo** [comment]
Perfect!

Thanks :)

**Comment by kanet77** [comment]
I'll update the readme. Thanks for letting me know about that error.

On Fri, Dec 11, 2015, 16:32 JV Lobo notifications-at-github.com |github| <
hr1ir7knet@sneakemail.com> wrote:

> Perfect!
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kanet77/togglv8/issues/9#issuecomment-164067062>.
>
-- 
Tom

--
@tomkane | 512.827.TOMK | ****************** |
http://www.linkedin.com/in/tominaustin
